/*
 * This source file was generated by the Gradle 'init' task
 */
package visual.studios.code;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  void theTestsWork() {
    assertEquals(true, true);
  }
}
