/*
 * This source file was generated by the Gradle 'init' task
 */
package zipit;

import java.util.ArrayList;
import java.util.List;

public class App {

    public static <T> List<T> zip(List<T> list1, List<T> list2) {

        
        List<T> result = new ArrayList<>();


        int i = 0;


        while (i < list1.size() && i < list2.size()) {
            result.add(list1.get(i));
            result.add(list2.get(i));
            i++;
        }



        while (i < list1.size()) result.add(list1.get(i++));
        while (i < list2.size()) result.add(list2.get(i++));

        return result;



    }

    public static void main(String[] args) {

        //numbers
        List<Integer> nums1 = List.of(1, 3, 5, 7);
        List<Integer> nums2 = List.of(2, 4, 6, 8);
        System.out.println("Here are the numbers in one list:");
        System.out.println(zip(nums1, nums2));

        //colors
        List<String> colors1 = List.of("Red", "Green", "Blue");
        List<String> colors2 = List.of("White", "Black", "Orange", "Pink", "Purple");
        System.out.println("\nHere are all of the colors in one list:");
        System.out.println(zip(colors1, colors2));



    }



}