/*
 * This source file was generated by the Gradle 'init' task
 */
package payroll;

import java.util.Scanner;

public class App {
    public int getNetPay(int h, int c) {

        double net;
        double gross;
        int rest;

        if(h > 40){

            rest = h - 40;
            gross = h * 16.78;
            gross = gross + (rest * 25.17);
            

        }

        else{

            gross = h * 16.78;

        }

        net = gross;
        net = net - ((gross/100) * 6); //social security
        net = net - ((gross/100) * 14); //federal income tax
        net = net - ((gross/100) * 5); //state income tax

        if(c >= 3){

            net = net - 45;

        }

        else{

            net = net - 25;

        }

        System.out.println("Payroll Stub\n");
        System.out.println("Hours Worked: " + h);
        System.out.println("Rate: $16.78/hr");
        System.out.println("Gross Pay: $" + String.format("%.2f", gross));

        System.out.println("Net Pay: $" + String.format("%.2f", net));



        return h;
    }

    public static void main(String[] args) {
        
        System.out.println("Welcome to the Payroll Program");
        Scanner scanner = new Scanner(System.in);

        System.out.println("\n");
        System.out.println("How many hours did you work this week? -> ");
        int hours = scanner.nextInt();
        System.out.println("How many children do you have? -> ");
        int children = scanner.nextInt();


        App app = new App();
        app.getNetPay(hours, children);
        scanner.close();











    }
}
