/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {
   //We have not learned how to test while loop with unit tests yet.
   //It is possible to do, but you need to handle the user input and validation
   //This, for this lab, you do NOT need to write unit tests
   //Instead, test your code with a driver function



}
