/*
 * This source file was generated by the Gradle 'init' task
 */
package success;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;

public class App {

    public static <T> ArrayList<T> removeDuplicates(ArrayList<T> list) {
        Set<T> set = new LinkedHashSet<>(list);
        return new ArrayList<>(set);
    }

    public static void main(String[] args) {
        
        System.out.println(removeDuplicates(new ArrayList<>())); 
        System.out.println(removeDuplicates(new ArrayList<>(Arrays.asList(1)))); 
        System.out.println(removeDuplicates(new ArrayList<>(Arrays.asList(1, 2, 3)))); 
        System.out.println(removeDuplicates(new ArrayList<>(Arrays.asList("A", "A", "B")))); 
        System.out.println(removeDuplicates(new ArrayList<>(Arrays.asList(1, 1, 3, 3, 5, 5)))); 
        
    }
}
