/*
 * This source file was generated by the Gradle 'init' task
 */
package success;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;
import java.util.ArrayList;
import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    

    @Test
    void testEmpty() {
        assertEquals(new ArrayList<>(), App.removeDuplicates(new ArrayList<>()));
    }



    @Test
    void testSingle() {
        assertEquals(
            new ArrayList<>(Arrays.asList(1)),
            App.removeDuplicates(new ArrayList<>(Arrays.asList(1)))
        );
    }


    @Test
    void testNoDuplicates() {
        assertEquals(
            new ArrayList<>(Arrays.asList(1, 2, 3)),
            App.removeDuplicates(new ArrayList<>(Arrays.asList(1, 2, 3)))
        );
    }


    @Test
    void testWithDuplicates() {
        assertEquals(
            new ArrayList<>(Arrays.asList("A", "B")),
            App.removeDuplicates(new ArrayList<>(Arrays.asList("A", "A", "B")))
        );
    }



    @Test
    void testMultipleDuplicates() {
        assertEquals(
            new ArrayList<>(Arrays.asList(1, 3, 5)),
            App.removeDuplicates(new ArrayList<>(Arrays.asList(1, 1, 3, 3, 5, 5)))
        );
    }


}