/*
 * This source file was generated by the Gradle 'init' task
 */
package zipit;

import org.junit.jupiter.api.Test;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void zipSameSize() {
        assertEquals(
            List.of(1, 10, 2, 20, 3, 30),
            App.zip(List.of(1, 2, 3), List.of(10, 20, 30))
        );
    }

    @Test
    void zipFirstLonger() {
        assertEquals(
            List.of(1, 10, 2, 20, 3, 4),
            App.zip(List.of(1, 2, 3, 4), List.of(10, 20))
        );
    }

    @Test
    void zipSecondLonger() {
        assertEquals(
            List.of(1, 10, 2, 20, 30, 40),
            App.zip(List.of(1, 2), List.of(10, 20, 30, 40))
        );
    }

    @Test
    void zipEmpty() {
        assertEquals(List.of(), App.zip(List.of(), List.of()));
        assertEquals(List.of(10, 20), App.zip(List.of(), List.of(10, 20)));
    }

    @Test
    void zipStrings() {
        assertEquals(
            List.of("A", "X", "B", "Y", "Z"),
            App.zip(List.of("A", "B"), List.of("X", "Y", "Z"))
        );
    }
}