/*
 * This source file was generated by the Gradle 'init' task
 */
package dishes;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void pushThenPop() {
        
        DishStack stack = new DishStack(1);
        stack.push(new Dish("Test"));
        assertEquals("Test", stack.pop().description);
        
    }

  
}
