/*
 * This source file was generated by the Gradle 'init' task
 */
package queuelab;

import java.util.ArrayList;





class Puppy implements Cutie {
    public String description() {
        return "A fluffy little puppy";
    }
    public Integer cutenessRating() {
        return 10;
    }
}

class Kitty implements Cutie {

    public String description() {

        return "A tiny adorable kitten";

    }

    public Integer cutenessRating() {

        return 9;

    }
}




class PygmyMarmoset implements Cutie {

    public String description() {

        return "The world's smallest monkey";
    }

    public Integer cutenessRating() {
        return 8;

    }
}

class QueueTees {



    private ArrayList<Cutie> items = new ArrayList<>();
    private int maxSize;




    public QueueTees(int maxSize) {
        this.maxSize = maxSize;
    }


    public void enqueue(Cutie cutie) {
        if (items.size() == maxSize) {
            System.out.println("The queue is full!");
            return;
        }
        items.add(cutie);
    }




    public Cutie dequeue() {
        if (items.isEmpty()) {
            System.out.println("The queue is empty!");
            return null;
        }
        Cutie first = items.get(0);
        items.remove(0);
        System.out.println("Dequeued: " + first.description() + " (Cuteness: " + first.cutenessRating() + "/10)");
        return first;
    }



    public int size() {
        return items.size();
    }






}

public class App {
    public static void main(String[] args) {
        Puppy puppy = new Puppy();
        Kitty kitty = new Kitty();
        PygmyMarmoset marmoset = new PygmyMarmoset();

        QueueTees queue = new QueueTees(3);

        System.out.println(queue.size()); 

        queue.enqueue(puppy);
        queue.enqueue(kitty);
        queue.enqueue(marmoset);

        System.out.println(queue.size()); 



        queue.dequeue();
        queue.dequeue(); 
        queue.dequeue(); 



    }
}