/*
 * This source file was generated by the Gradle 'init' task
 */
package visual.studios.code;

import java.util.ArrayList;

public class App {
  public static void main(String[] args) {

    FuzzyListGenerator gen = new FuzzyListGenerator(5);

    ArrayList<Fuzzy> randomList = gen.randomizedRainbowFuzzies();
    ArrayList<Fuzzy> sortedList = gen.sortedRainbowFuzzies();

    LinearSearch ls1 = new LinearSearch(randomList);
    System.out.println("Linear Random: " + ls1.searchGoldFuzzy());

    LinearSearch ls2 = new LinearSearch(sortedList);
    System.out.println("Linear Sorted: " + ls2.searchGoldFuzzy());

    BinarySearch bs1 = new BinarySearch(randomList);
    System.out.println("Binary Random: " + bs1.searchGoldFuzzy());

    BinarySearch bs2 = new BinarySearch(sortedList);
    System.out.println("Binary Sorted: " + bs2.searchGoldFuzzy());
  }
}
