/*
 * This source file was generated by the Gradle 'init' task
 */
package visual.studios.code;

import java.util.ArrayList;

public class App {
  public static void main(String[] args) {

    FuzzyListGenerator generator = new FuzzyListGenerator(5);

    ArrayList<Fuzzy> randomList = generator.randomizedRainbowFuzzies();
    ArrayList<Fuzzy> sortedList = generator.sortedRainbowFuzzies();

    Search randomSearch = new Search(randomList);
    Search sortedSearch = new Search(sortedList);

    System.out.println("Linear Random: " + randomSearch.linearSearch());
    System.out.println("Linear Sorted: " + sortedSearch.linearSearch());

    System.out.println("Binary Random: " + randomSearch.binarySearch());
    System.out.println("Binary Sorted: " + sortedSearch.binarySearch());
  }
}
