/*
 * This source file was generated by the Gradle 'init' task
 */
package tictactoe;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class AppTest {

    TicTacToe game;

    @BeforeEach
    void setup() {
        game = new TicTacToe();
    }

    @Test
    void testPlayerOneWins() {
        game.playerOne(1);
        game.playerOne(2);
        game.playerOne(3);
        game.checkOne();
        assertTrue(game.win1);
    }

    @Test
    void testPlayerTwoWins() {
        game.playerTwo(1);
        game.playerTwo(2);
        game.playerTwo(3);
        game.checkTwo();
        assertTrue(game.win2);
    }

    @Test
    void testTie() {
        game.playerOne(1);
        game.playerTwo(2);
        game.playerOne(3);
        game.playerOne(4);
        game.playerTwo(5);
        game.playerTwo(6);
        game.playerTwo(7);
        game.playerOne(8);
        game.playerOne(9);
        game.checkTie();
        assertTrue(game.tie);
    }




}
