/*
 * This source file was generated by the Gradle 'init' task
 */
package dishes;

public class App {

    public static void main(String[] args) {

         DishStack stack = new DishStack(4);

        Dish oneDish = new Dish("A dish with one fish pattern on it");
        Dish twoDish = new Dish("A dish with two fish patterns on it");
        Dish redDish = new Dish("A dish with a red fish pattern on it");
        Dish blueDish = new Dish("A dish with a blue fish pattern on it");

        System.out.println("Initial size ->\t\t" + stack.size());

        stack.push(oneDish);
        stack.push(twoDish);
        stack.push(redDish);
        stack.push(blueDish);

        System.out.println("Size after pushes ->\t" + stack.size());
        System.out.println("Top item ->\t\t" + stack.peek().description);
        System.out.println("Popped ->\t\t" + stack.pop().description);
        System.out.println("Popped ->\t\t" + stack.pop().description);
        System.out.println("Final size ->\t\t" + stack.size());



    }
}