/*
 * This source file was generated by the Gradle 'init' task
 */
package queuelab;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {



    @Test
    void queueStartsEmpty() {
        assertEquals(0, new QueueTees(3).size());
    }



    @Test
    void enqueueAddsToQueue() {
        var queue = new QueueTees(3);
        queue.enqueue(new Puppy());
        assertEquals(1, queue.size());
    }



    



    @Test
    void dequeueRemovesFromQueue() {
        var queue = new QueueTees(3);
        queue.enqueue(new Puppy());
        queue.dequeue();
        assertEquals(0, queue.size());
    }



    @Test
    void dequeueFollowsFIFO() {
        var queue = new QueueTees(3);
        var puppy = new Puppy();
        var kitty = new Kitty();
        var marmoset = new PygmyMarmoset();
        queue.enqueue(puppy);
        queue.enqueue(kitty);
        queue.enqueue(marmoset);
        assertSame(puppy, queue.dequeue());
        assertSame(kitty, queue.dequeue());
        assertSame(marmoset, queue.dequeue());
    }






    @Test
    void fullQueueIsUnchanged() {
        var queue = new QueueTees(2);
        queue.enqueue(new Puppy());
        queue.enqueue(new Kitty());
        queue.enqueue(new PygmyMarmoset());
        assertEquals(2, queue.size());
    }




    @Test
    void dequeueOnEmptyReturnsNull() {
        assertNull(new QueueTees(3).dequeue());
    }




    @Test
    void sizeTracksCorrectly() {
        var queue = new QueueTees(3);
        queue.enqueue(new Puppy());
        queue.enqueue(new Kitty());
        queue.dequeue();
        queue.enqueue(new PygmyMarmoset());
        assertEquals(2, queue.size());
    }





}