/*
 * This source file was generated by the Gradle 'init' task
 */
package cheese;

public class App {

    public static void main(String[] args) {
        Cheese c = new Cheese();
        c.start();
    }
}