/*
 * This source file was generated by the Gradle 'init' task
 */
package recursionlab;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {

    @Test
    public void testTriangleNumberCalculator() {
        TriangleNumberCalculator calculator = new TriangleNumberCalculator();

        assertEquals(1, calculator.value(1));
        assertEquals(3, calculator.value(2));
        assertEquals(10, calculator.value(4));

        assertEquals(2, calculator.add(1, 1));
        assertEquals(8, calculator.add(2, 3));
        assertEquals(16, calculator.add(4, 2));

        assertEquals(0, calculator.subtract(1, 1));
        assertEquals(-4, calculator.subtract(2, 3));
        assertEquals(4, calculator.subtract(4, 2));
    }

    
}