/*
 * This source file was generated by the Gradle 'init' task
 */

package tictactoe;

import java.util.Scanner;

public class App {

  public static void main(String[] args) {

    Scanner scan = new Scanner(System.in);
    TicTacToe play = new TicTacToe();
    FileWrite file = new FileWrite();
    String answer = "y";

    int player1Wins = 0;
    int player2Wins = 0;
    int ties = 0;

    boolean player1First = true;

    System.out.println("Welcome to Tic Tac Toe!\n\n");

    while (answer.equalsIgnoreCase("y")) {

      while (play.win1 == false && play.win2 == false && play.tie == false) {

        if (player1First == true) {

          play.board();

          System.out.print("\n\n");
          System.out.print("\nPlayer 1, please choose a cell -> ");

          String inputLine = scan.nextLine();

          while (!inputLine.matches("[1-9]")) {
            System.out.print("Invalid input. Please enter a number -> ");
            inputLine = scan.nextLine();
          }

          int x = Integer.parseInt(inputLine);

          play.inputCheck(x);
          while (play.input == false) {
            System.out.print("Invalid input. Please enter a number -> ");
            inputLine = scan.nextLine();

            while (!inputLine.matches("[1-9]")) {
              System.out.print("Invalid input. Please enter a number -> ");
              inputLine = scan.nextLine();
            }

            x = Integer.parseInt(inputLine);
            play.inputCheck(x);
          }

          play.playerOne(x);

          play.checkOne();
          play.checkTwo();
          play.checkTie();

          if (play.win1 == true || play.win2 == true || play.tie == true) {
          } else {

            play.board();
            System.out.print("\n\n");
            System.out.print("\nPlayer 2, please choose a cell -> ");

            inputLine = scan.nextLine();

            while (!inputLine.matches("[1-9]")) {
              System.out.print("Invalid input. Please enter a number -> ");
              inputLine = scan.nextLine();
            }

            x = Integer.parseInt(inputLine);

            play.inputCheck(x);
            while (play.input == false) {
              System.out.print("Invalid input. Please enter a number -> ");
              inputLine = scan.nextLine();

              while (!inputLine.matches("[1-9]")) {
                System.out.print("Invalid input. Please enter a number -> ");
                inputLine = scan.nextLine();
              }

              x = Integer.parseInt(inputLine);
              play.inputCheck(x);
            }

            play.playerTwo(x);
          }

        } else {

          play.board();
          System.out.print("\n\n");
          System.out.print("\nPlayer 2, please choose a cell -> ");

          String inputLine = scan.nextLine();

          while (!inputLine.matches("[1-9]")) {
            System.out.print("Invalid input. Please enter a number -> ");
            inputLine = scan.nextLine();
          }

          int x = Integer.parseInt(inputLine);

          play.inputCheck(x);
          while (play.input == false) {
            System.out.print("Invalid input. Please enter a number -> ");
            inputLine = scan.nextLine();

            while (!inputLine.matches("[1-9]")) {
              System.out.print("Invalid input. Please enter a number -> ");
              inputLine = scan.nextLine();
            }

            x = Integer.parseInt(inputLine);
            play.inputCheck(x);
          }

          play.playerTwo(x);

          play.checkOne();
          play.checkTwo();
          play.checkTie();

          if (play.win1 == true || play.win2 == true || play.tie == true) {
          } else {

            play.board();
            System.out.print("\n\n");
            System.out.print("\nPlayer 1, please choose a cell -> ");

            inputLine = scan.nextLine();

            while (!inputLine.matches("[1-9]")) {
              System.out.print("Invalid input. Please enter a number -> ");
              inputLine = scan.nextLine();
            }

            x = Integer.parseInt(inputLine);

            play.inputCheck(x);
            while (play.input == false) {
              System.out.print("Invalid input. Please enter a number -> ");
              inputLine = scan.nextLine();

              while (!inputLine.matches("[1-9]")) {
                System.out.print("Invalid input. Please enter a number -> ");
                inputLine = scan.nextLine();
              }

              x = Integer.parseInt(inputLine);
              play.inputCheck(x);
            }

            play.playerOne(x);
          }
        }

        play.checkOne();
        play.checkTwo();
        play.checkTie();
      }

      System.out.print("\n\n");
      play.board();
      System.out.print("\n\n");

      if (play.win1 == true) {
        System.out.println("Congratulations Player 1, you win!");
        player1Wins++;
        player1First = false;
      } else if (play.win2 == true) {
        System.out.println("Congratulations Player 2, you win!");
        player2Wins++;
        player1First = true;
      } else if (play.tie == true) {
        System.out.println("It's a tie!");
        ties++;
      }

      System.out.println("\nThe current log is:\n");
      System.out.println("Player 1 Wins   " + player1Wins);
      System.out.println("Player 2 Wins   " + player2Wins);
      System.out.println("Ties            " + ties);

      System.out.print("\n\n");
      System.out.print("Would you like to play again? (Y/N) -> ");

      answer = scan.nextLine();

      while (!answer.equalsIgnoreCase("y") && !answer.equalsIgnoreCase("n")) {
        System.out.print("Invalid input. Enter y or n -> ");
        answer = scan.nextLine();
      }

      if (answer.equalsIgnoreCase("y")) {
        play.resetGame();
      }
    }

    file.write(player1Wins, player2Wins, ties);
  }
}