/*
 * This source file was generated by the Gradle 'init' task
 */
package tictactoe;

import java.util.Scanner;

public class App {

  public static void main(String[] args) {

    Scanner scan = new Scanner(System.in);
    TicTacToe play = new TicTacToe();
    String answer = "y";

    System.out.println("Welcome to Tic Tac Toe!\n\n");

    while (answer.equalsIgnoreCase("y")) {
      while (play.win1 == false && play.win2 == false && play.tie == false) {

        if (play.win1 == true || play.win2 == true || play.tie == true) {
        } else {
          play.board();

          System.out.print("\n\n");
          System.out.print("\nPlayer 1, please choose a cell -> ");

          while (!scan.hasNextInt()) {
            System.out.print("Invalid input. Please enter a number -> ");
            scan.next();
          }

          int x = scan.nextInt();
          play.inputCheck(x);
          if (play.input == true) {
            play.playerOne(x);
          } else if (play.input == false) {
            while (play.input == false) {
              System.out.print("Invalid input. Please enter a number -> ");

              while (!scan.hasNextInt()) {
                System.out.print("Invalid input. Please enter a number -> ");
                scan.next();
              }

              x = scan.nextInt();
              play.inputCheck(x);
            }
            play.playerOne(x);
          }

        }
        play.checkOne();
        play.checkTwo();
        play.checkTie();
        if (play.win1 == true || play.win2 == true || play.tie == true) {
        } else {
          play.board();
          System.out.print("\n\n");
          System.out.print("\nPlayer 2, please choose a cell -> ");
          while (!scan.hasNextInt()) {
            System.out.print("Invalid input. Please enter a number -> ");
            scan.next();
          }

          int x = scan.nextInt();
          play.inputCheck(x);
          if (play.input == true) {
            play.playerTwo(x);
          } else if (play.input == false) {
            while (play.input == false) {
              System.out.print("Invalid input. Please enter a number -> ");

              while (!scan.hasNextInt()) {
                System.out.print("Invalid input. Please enter a number -> ");
                scan.next();
              }

              x = scan.nextInt();
              play.inputCheck(x);
            }
            play.playerTwo(x);
          }

        }
        play.checkOne();
        play.checkTwo();
        play.checkTie();

      }

      System.out.print("\n\n");
      play.board();
      System.out.print("\n\n");
      if (play.win1 == true) {
        System.out.println("Congratulations Player 1, you win!");
      } else if (play.win2 == true) {
        System.out.println("Congratulations Player 2, you win!");
      } else if (play.tie == true) {
        System.out.println("It's a tie!");
      }

      System.out.print("\n\n");
      System.out.print("Would you like to play again? (Y/N) -> ");

      answer = scan.next();

      while (!answer.equalsIgnoreCase("y") && !answer.equalsIgnoreCase("n")) {
        System.out.print("Invalid input. Enter y or n -> ");
        answer = scan.next();
      }

      if (answer.equalsIgnoreCase("y")) {
        play.resetGame();
      }

    }
  }
}
